apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: temporal
resources:
- ./secrets/temporal-default-store-secret.yaml
- ./secrets/temporal-es-visibility-store-secret.yaml
- ./secrets/temporal-visibility-store-secret.yaml
- temporal-admintools-deployment.yaml
- temporal-admintools-service.yaml
- temporal-backendconfig.yaml
- temporal-dynamic-configmap.yaml
- temporal-frontend-configmap.yaml
- temporal-frontend-deployment.yaml
- temporal-frontend-headless-service.yaml
- temporal-frontend-service.yaml
- temporal-history-configmap.yaml
- temporal-history-deployment.yaml
- temporal-history-headless-service.yaml
- temporal-web-ingress.yaml
- temporal-kube-state-metrics-serviceaccount.yaml
- temporal-matching-configmap.yaml
- temporal-matching-deployment.yaml
- temporal-matching-headless-service.yaml
- temporal-web-configmap.yaml
- temporal-web-deployment.yaml
- temporal-web-service.yaml
- temporal-worker-configmap.yaml
- temporal-worker-deployment.yaml
- temporal-worker-headless-service.yaml
