apiVersion: apps/v1
kind: Deployment
metadata:
  name: temporal-web
  namespace: temporal
  labels:
    app.kubernetes.io/name: temporal
    app.kubernetes.io/instance: temporal
    app.kubernetes.io/component: web
    app.kubernetes.io/part-of: temporal
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: temporal
      app.kubernetes.io/instance: temporal
      app.kubernetes.io/component: web
  template:
    metadata:
      labels:
        app.kubernetes.io/name: temporal
        app.kubernetes.io/instance: temporal
        app.kubernetes.io/component: web
        app.kubernetes.io/part-of: temporal
    spec:

      volumes:
        - name: temporal-web-config
          configMap:
            name: temporal-web-config
      containers:
        - name: temporal-web
          image: "temporalio/ui:2.17.2"
          imagePullPolicy: IfNotPresent
          env:
            - name: TEMPORAL_ADDRESS
              value: "temporal-frontend.temporal.svc:7233"
          ports:
            - name: https
              containerPort: 8080
              protocol: TCP
          resources:
            {}