apiVersion: v1
kind: Service
metadata:
  name: temporal-web
  namespace: temporal
  labels:
    app.kubernetes.io/name: temporal
    app.kubernetes.io/instance: temporal
    app.kubernetes.io/component: web
    app.kubernetes.io/part-of: temporal
  annotations:
    cloud.google.com/backend-config: '{"default": "temporal-backendconfig"}'
spec:
  type: NodePort
  ports:
    - port: 8080
      targetPort: https
      protocol: TCP
      name: https
  selector:
    app.kubernetes.io/name: temporal
    app.kubernetes.io/instance: temporal
    app.kubernetes.io/component: web