apiVersion: v1
kind: ConfigMap
metadata:
  name: temporal-dynamic-config
  namespace: temporal
  labels:
    app.kubernetes.io/name: temporal
    app.kubernetes.io/instance: temporal
    app.kubernetes.io/part-of: temporal
data:
  dynamic_config.yaml: |-