apiVersion: argoproj.io/v1alpha1
kind: Sensor
metadata:
  name: webhook
  namespace: argo-events
spec:
  template:
    serviceAccountName: operate-workflow-sa
  dependencies:
    - name: cicd-dep
      eventSourceName: webhook
      eventName: cicd
  triggers:
    - template:
        name: argo-cicd-trigger
        argoWorkflow:
          operation: submit
          source:
            resource:
              apiVersion: argoproj.io/v1alpha1
              kind: Workflow
              metadata:
                generateName: cicd-from-webhook-
                namespace: argocd
              spec:
                arguments:
                  parameters:
                    - name: dockerfile
                    - name: tag
                    - name: branch
                    - name: repo
                    - name: project
                    - name: destination
                workflowTemplateRef:
                  name: base-image-kaniko-clone-build-push
          parameters:
            - src:
                dependencyName: cicd-dep
                dataKey: body.dockerfile
                value: Dockerfile
              dest: spec.arguments.parameters.0.value
            - src:
                dependencyName: cicd-dep
                dataKey: body.tag
                value: latest
              dest: spec.arguments.parameters.1.value
            - src:
                dependencyName: cicd-dep
                dataKey: body.branch
                value: master
              dest: spec.arguments.parameters.2.value
            - src:
                dependencyName: cicd-dep
                dataKey: body.repo
                value: https://gitlab.com/<YOUR_GITLAB_GROUP>/<REPO_NAME>.git
              dest: spec.arguments.parameters.3.value
            - src:
                dependencyName: cicd-dep
                dataKey: body.project
              dest: spec.arguments.parameters.4.value
            - src:
                dependencyName: cicd-dep
                dataKey: body.destination
                value: asia.gcr.io/acme-preproduction
              dest: spec.arguments.parameters.5.value