apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: argo-events
bases:
- github.com/argoproj/argo-events/manifests/namespace-install

resources:
- https://raw.githubusercontent.com/argoproj/argo-events/stable/examples/eventbus/native.yaml
- namespace.yaml
- sensor-rbac.yaml
- cicd-trigger.yaml
- webhook.yaml