apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

labels:
  - pairs:
      env: prod
    includeSelectors: false

resources:
  - ../../base
  - temporal-cert.yaml

patches:
  - target:
      version: v1
      kind: Service
      name: temporal-frontend
    path: ./patches/temporal-frontend-service-patch.yaml
  - target:
      version: v1
      kind: Ingress
      name: temporal-web-ingress
    path: ./patches/temporal-web-ingress-patch.yaml
