apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: gcp-secrets-manager
spec:
  provider:
    gcpsm:
      projectID: <GCP_QA_PROJECT>
      auth:
        secretRef:
          secretAccessKeySecretRef:
            name: gcp-secret-manager-credentials
            namespace: external-secrets
            key: credentials.json