apiVersion: v1
kind: Service
metadata:
  name: kafka-connect-metrics
  labels:
    app: kafka-connect
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "5556"
    prometheus.io/path: "/metrics"
spec:
  ports:
    - name: jmx-metrics
      port: 5556
  selector:
    app: kafka-connect
