apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: kafka-connect-databases-credentials
spec:
  refreshInterval: "3m"
  secretStoreRef:
    name: gcp-enterprise-secret-manager
    kind: ClusterSecretStore
  target:
    name: kafka-connect-databases-credentials
    template:
      data:
        connect-secrets.properties: |
          mongodb-user={{ .mongodb_user }}
          mongodb-password={{ .mongodb_password }}

  data:
    - secretKey: mongodb_user
      remoteRef:
        key: kafka-connect-databases-credentials
        property: mongodb.uat.kafkastream_user
    - secretKey: mongodb_password
      remoteRef:
        key: kafka-connect-databases-credentials
        property: mongodb.uat.kafkastream_user_password