apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: kafka-qa

labels:
- pairs:
    env: qa

patches:
- path: deployment-patch.yaml
  target:
    kind: Deployment
    name: kafka-connect
- path: kafka-connect-node-patch.yaml
  target:
    kind: Deployment
    name: kafka-connect
- path: kafka-connect-config-patch.yaml
  target:
    kind: Deployment
    name: kafka-connect

resources:
- ../../base
- externalsecret.yaml
