apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: common-secrets
spec:
  refreshInterval: 1m
  secretStoreRef:
    name: gcp-prod-consumer-secret-store
    kind: ClusterSecretStore
  target:
    name: common-secrets
    creationPolicy: Owner
  dataFrom:
    - extract:
        key: consumer-common-secrets-argocd