apiVersion: v1
kind: ServiceAccount
metadata:
  name: default
  namespace: enterprise-cms-qa-th
  annotations:
    # This annotation tells Istio to route traffic through the waypoint proxy
    # for all pods using this ServiceAccount (which is most pods by default)
    istio.io/use-waypoint: waypoint
