---
apiVersion: telemetry.istio.io/v1
kind: Telemetry
metadata:
  name: waypoint-metrics
  namespace: enterprise-cms-qa-th
spec:
  targetRef:
    group: gateway.networking.k8s.io
    kind: Gateway
    name: waypoint
  metrics:
  - providers:
    - name: prometheus
