apiVersion: v1
kind: Secret
metadata:
  name: temporal-es-visibility-store
  namespace: temporal
  labels:
    app.kubernetes.io/name: temporal
    app.kubernetes.io/instance: temporal
    app.kubernetes.io/part-of: temporal
type: Opaque
data:
  es-kube-username: "<BASE64_ES_USERNAME>"   # echo -n 'your-user' | base64
  es-kube-password: "<BASE64_ES_PASSWORD>"   # echo -n 'your-password' | base64