apiVersion: v1
kind: Secret
metadata:
  name: temporal-visibility-store
  namespace: temporal
  labels:
    app.kubernetes.io/name: temporal
    app.kubernetes.io/instance: temporal
    app.kubernetes.io/part-of: temporal
type: Opaque
data:
  password: "cGFzc3dvcmQ="