apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: kafka-connect-databases-credentials
spec:
  refreshInterval: "3m"
  secretStoreRef:
    name: gcp-prod-enterprise-secret-store
    kind: ClusterSecretStore
  target:
    name: kafka-connect-databases-credentials
    template:
      data:
        connect-secrets.properties: |
          enterprise-my-mongodb-write-user={{ .enterprise_my_mongodb_write_user }}
          enterprise-my-mongodb-write-user-password={{ .enterprise_my_mongodb_write_user_password }}
          enterprise-my-mongodb-read-user={{ .enterprise_my_mongodb_read_user }}
          enterprise-my-mongodb-read-user-password={{ .enterprise_my_mongodb_read_user_password }}
          enterprise-id-mongodb-write-user={{ .enterprise_id_mongodb_write_user }}
          enterprise-id-mongodb-write-user-password={{ .enterprise_id_mongodb_write_user_password }}

  data:
    # mongodb acme-my-prod-cluster
    - secretKey: enterprise_my_mongodb_write_user
      remoteRef:
        key: kafka-connect-databases-credentials
        property: mongodb.acme-my-prod-cluster.kafkastream_user
    - secretKey: enterprise_my_mongodb_write_user_password
      remoteRef:
        key: kafka-connect-databases-credentials
        property: mongodb.acme-my-prod-cluster.kafkastream_user_password
    - secretKey: enterprise_my_mongodb_read_user
      remoteRef:
        key: kafka-connect-databases-credentials
        property: mongodb.acme-my-prod-cluster.kafkastream_read_user
    - secretKey: enterprise_my_mongodb_read_user_password
      remoteRef:
        key: kafka-connect-databases-credentials
        property: mongodb.acme-my-prod-cluster.kafkastream_read_user_password
    # mongodb acme-id-prod-cluster
    - secretKey: enterprise_id_mongodb_write_user
      remoteRef:
        key: kafka-connect-databases-credentials
        property: mongodb.acme-id-prod-cluster.kafkastream_user
    - secretKey: enterprise_id_mongodb_write_user_password
      remoteRef:
        key: kafka-connect-databases-credentials
        property: mongodb.acme-id-prod-cluster.kafkastream_user_password