apiVersion: v1
kind: Service
metadata:
  labels:
    app: debezium-ui
  name: debezium-ui
spec:
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
  selector:
    app: debezium-ui
---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: debezium-ui
spec:
  selector:
    matchLabels:
      app: debezium-ui
  replicas: 1
  template:
    metadata:
      labels:
        app: debezium-ui
    spec:
      containers:
        - name: debezium-ui
          image: debezium/debezium-ui:latest
          env:
            - name: KAFKA_CONNECT_URIS
              value: http://debezium:8083