apiVersion: v1
kind: ConfigMap
metadata:
  name: debezium-jmx-exporter-config
data:
  jmx-exporter-config.yaml: |
    lowercaseOutputName: true
    lowercaseOutputLabelNames: true
    rules:
    - pattern: debezium.([^:]+)<type=connector-metrics, context=([^,]+), server=([^,>]+)><>([^:]+)
      name: debezium_$1_connector_$4
      labels:
        context: $2
        server: $3
      type: GAUGE
    - pattern: debezium.([^:]+)<type=connector-metrics, context=([^,]+), server=([^,]+), task=([^,>]+)><>([^:]+)
      name: debezium_$1_connector_task_$5
      labels:
        context: $2
        server: $3
        task: $4
      type: GAUGE
    - pattern: kafka.connect<type=connect-worker-metrics><>([^:]+)
      name: kafka_connect_worker_$1
      type: GAUGE
    - pattern: kafka.connect<type=connect-worker-rebalance-metrics><>([^:]+)
      name: kafka_connect_worker_rebalance_$1
      type: GAUGE
    - pattern: kafka.connect<type=connector-metrics, connector=([^,]+)><>([^:]+)
      name: kafka_connect_connector_$2
      labels:
        connector: $1
      type: GAUGE
    - pattern: kafka.connect<type=task-metrics, connector=([^,]+), task=([^,]+)><>([^:]+)
      name: kafka_connect_task_$3
      labels:
        connector: $1
        task: $2
      type: GAUGE
    - pattern: java.lang<type=([^,]+), name=([^,>]+)><>([^:]+)
      name: java_lang_$1_$3
      labels:
        name: $2
      type: GAUGE
    - pattern: java.lang<type=Memory><>([^:]+)
      name: java_lang_memory_$1
      type: GAUGE
    - pattern: kafka.connect<type=([^,]+), name=([^,>]+)><>([^:]+)
      name: kafka_connect_$1_$3
      labels:
        name: $2
      type: GAUGE
    - pattern: debezium\.([^:]+)<type=([^,>]+), (.*)><>([^:]+)
      name: debezium_$2_$4
      type: GAUGE
