apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: kafka
labels:
  - includeSelectors: false
    pairs:
      app.kubernetes.io/component: debezium
  - includeSelectors: false
    pairs:
      env: stg
resources:
- deployment.yaml
- service.yaml
- debezium-ui.yaml
- jmx-exporter-config.yaml
- service-metrics.yaml
- servicemonitor.yaml
