{
 "title": "Mimir / Overview",
 "tags": [ "mimir" ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Data source", "query": "prometheus" },
   {
    "name": "cluster",
    "label": "Cluster",
    "query": {
     "query": "label_values(cortex_build_info, cluster)"
    }
   },
   {
    "name": "namespace",
    "label": "Namespace",
    "query": {
     "query": "label_values(cortex_build_info{cluster=~\"$cluster\"}, namespace)"
    }
   },
   { "name": "latency_metrics", "label": "Latency metrics", "query": "native : -1,classic : 1" }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 0 },
   "options": {
    "content": "The 'Status' panel shows an overview on the cluster health over the time.\nTo investigate failures, see a specific dashboard:\n\n- Writes\n- Reads\n- Rule evaluations\n- Alerting notifications\n- Object storage"
   }
  },
  {
   "title": "Status",
   "type": "state-timeline",
   "gridPos": { "h": 6, "w": 12, "x": 6, "y": 0 },
   "targets": [
    {
     "expr": "((sum(histogram_count(rate(cortex_request_duration_seconds{cluster=~\"$cluster\", job=~\"($namespace)/((distributor.*|cortex|mimir))\", route=~\"/distributor.Distributor/Push|/httpgrpc.*|api_(v1|prom)_push|otlp_v1_metrics|api_v1_push_influx_write\",status_code=~\"5.*|error\"}[$__rate_interval]))) or vector(0)) / sum(histogram_count(rate(cortex_request_duration_seconds{cluster=~\"$cluster\", job=~\"($namespace)/((distributor.*|cortex|mimir))\", route=~\"/distributor.Distributor/Push|/httpgrpc.*|api_(v1|prom)_push|otlp_v1_metrics|api_v1_push_influx_write\"}[$__rate_interval])))) and on() (vector($latency_metrics) == -1)",
     "legendFormat": "Writes"
    }
   ]
  },
  { "title": "Firing alerts", "type": "alertlist", "gridPos": { "h": 6, "w": 6, "x": 18, "y": 0 } },
  { "type": "text", "gridPos": { "h": 2, "w": 24, "x": 0, "y": 6 }, "options": { "content": "## Writes" } },
  {
   "type": "text",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 8 },
   "options": {
    "content": "These panels show an overview on the write path."
   }
  },
  {
   "title": "Write requests / sec",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "(sum by (status) (label_replace(label_replace(rate(cortex_request_duration_seconds_count{cluster=~\"$cluster\", job=~\"($namespace)/((distributor.*|cortex|mimir))\", route=~\"/distributor.Distributor/Push|/httpgrpc.*|api_(v1|prom)_push|otlp_v1_metrics|api_v1_push_influx_write\"}[$__rate_interval]), \"status\", \"${1}xx\", \"status_code\", \"([0-9])..\"), \"status\", \"${1}\", \"status_code\", \"([a-zA-Z]+)\"))) and on() (vector($latency_metrics) == 1)",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "Write latency",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "(histogram_quantile(0.99, sum by (le) (cluster_job_route:cortex_request_duration_seconds_bucket:sum_rate{cluster=~\"$cluster\", job=~\"($namespace)/((distributor.*|cortex|mimir))\", route=~\"/distributor.Distributor/Push|/httpgrpc.*|api_(v1|prom)_push|otlp_v1_metrics|api_v1_push_influx_write\"})) * 1e3) and on() (vector($latency_metrics) == 1)",
     "legendFormat": "99th percentile"
    }
   ]
  },
  {
   "title": "Ingestion / sec",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "cps" } },
   "targets": [
    {
     "expr": "sum(cluster_namespace_job:cortex_distributor_received_samples:rate5m{cluster=~\"$cluster\", job=~\"($namespace)/((distributor.*|cortex|mimir))\"})",
     "legendFormat": "samples / sec"
    }
   ]
  },
  { "type": "text", "gridPos": { "h": 2, "w": 24, "x": 0, "y": 14 }, "options": { "content": "## Reads" } },
  {
   "title": "Read requests / sec",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "(sum by (status) (label_replace(label_replace(rate(cortex_request_duration_seconds_count{cluster=~\"$cluster\", job=~\"($namespace)/((query-frontend.*|cortex|mimir))\", route=~\"(prometheus|api_prom)_api_v1_.+\"}[$__rate_interval]), \"status\", \"${1}xx\", \"status_code\", \"([0-9])..\"), \"status\", \"${1}\", \"status_code\", \"([a-zA-Z]+)\"))) and on() (vector($latency_metrics) == 1)",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "Read latency",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "(histogram_quantile(0.99, sum by (le) (cluster_job_route:cortex_request_duration_seconds_bucket:sum_rate{cluster=~\"$cluster\", job=~\"($namespace)/((query-frontend.*|cortex|mimir))\", route=~\"(prometheus|api_prom)_api_v1_.+\"})) * 1e3) and on() (vector($latency_metrics) == 1)",
     "legendFormat": "99th percentile"
    }
   ]
  },
  {
   "title": "Queries / sec",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "(sum by (route) (rate(cortex_request_duration_seconds_count{cluster=~\"$cluster\", job=~\"($namespace)/((query-frontend.*|cortex|mimir))\",route=~\"(prometheus|api_prom)(_api_v1_query|_api_v1_query_range)\"}[$__rate_interval]))) and on() (vector($latency_metrics) == 1)"
    }
   ]
  },
  { "type": "text", "gridPos": { "h": 2, "w": 24, "x": 0, "y": 22 }, "options": { "content": "## Object Storage" } },
  {
   "title": "Object Storage Requests / sec",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(thanos_objstore_bucket_operations_total{cluster=~\"$cluster\", namespace=~\"$namespace\"}[$__rate_interval])) - sum(rate(thanos_objstore_bucket_operation_failures_total{cluster=~\"$cluster\", namespace=~\"$namespace\"}[$__rate_interval]))",
     "legendFormat": "successful"
    }
   ]
  },
  {
   "title": "Operations / sec",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by(operation) (rate(thanos_objstore_bucket_operations_total{cluster=~\"$cluster\", namespace=~\"$namespace\"}[$__rate_interval]))",
     "legendFormat": "{{operation}}"
    }
   ]
  },
  {
   "title": "Total blocks in storage",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(max by(user) (max_over_time(cortex_bucket_blocks_count{cluster=~\"$cluster\", job=~\"($namespace)/((compactor.*|cortex|mimir))\"}[15m])))",
     "legendFormat": "blocks"
    }
   ]
  }
 ]
}