apiVersion: v1
kind: Service
metadata:
  name: zk-kafka-svc
  labels:
    app: zk-kafka-svc
spec:
  ports:
    - port: 2181
      name: client
    - port: 2888
      name: server
    - port: 3888
      name: leader-election
  clusterIP: None
  selector:
    app: zk-kafka
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: zk-kafka-cm
data:
  tick: "2000"
  servers: "zk-kafka-0.zk-kafka-svc.default.svc.cluster.local:2888:3888;zk-kafka-1.zk-kafka-svc.default.svc.cluster.local:2888:3888;zk-kafka-2.zk-kafka-svc.default.svc.cluster.local:2888:3888"
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: zk-kafka-pdb
spec:
  selector:
    matchLabels:
      app: zk-kafka
  minAvailable: 2
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: zk-kafka
spec:
  serviceName: zk-kafka-svc
  replicas: 3
  selector:
    matchLabels:
      app: zk-kafka
  podManagementPolicy: Parallel
  template:
    metadata:
      labels:
        app: zk-kafka
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: "app"
                    operator: In
                    values:
                      - zk-kafka
              topologyKey: "kubernetes.io/hostname"
      containers:
        - name: k8szk-kafka
          imagePullPolicy: Always
          image: confluentinc/cp-zookeeper:5.4.0
          command:
            - "bash"
            - "-c"
            - "export ZOOKEEPER_SERVER_ID=$((${HOSTNAME##*-}+1))
              && ls -al /opt/configs
              && sh /opt/configs/copy_config.sh
              && /etc/confluent/docker/run"
          resources: {{ resources_zk }}
          ports:
            - containerPort: 2181
              name: client
            - containerPort: 2888
              name: server
            - containerPort: 3888
              name: leader-election
          env:
            - name: ZOOKEEPER_TICK_TIME
              valueFrom:
                configMapKeyRef:
                  name: zk-kafka-cm
                  key: tick
            - name: ZOOKEEPER_SYNC_LIMIT
              valueFrom:
                configMapKeyRef:
                  name: zk-kafka-cm
                  key: tick
            - name: ZOOKEEPER_SERVERS
              valueFrom:
                configMapKeyRef:
                  name: zk-kafka-cm
                  key: servers
            - name: ZOOKEEPER_CLIENT_PORT
              value: "2181"
            - name: ZOOKEEPER_LOG4J_ROOT_LOGLEVEL
              value: "WARN"
          volumeMounts:
            - name: datadir
              mountPath: /var/lib/zookeeper
            - name: zk-configmap-volume
              mountPath: /opt/configs
      volumes:
        - name: zk-configmap-volume
          configMap:
            name: zk-configmap
      nodeSelector: {{ node_selector }}
      tolerations: {{ tolerations }}
  volumeClaimTemplates:
    - metadata:
        name: datadir
        annotations:
          volume.beta.kubernetes.io/storage-class: "ssd-expand"
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 5Gi