apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: kafka-qa

labels:
  - includeSelectors: false
    pairs:
      env: qa

patches:
- path: ksql-deployment-patch.yaml
  target:
    kind: Deployment
    name: ksql

resources:
  - ../../base
